sudo: required
services:
 - docker
before_install:
 - docker build -t shayankureshi/react-test -f ./client/Dockerfile.dev ./client
script:
 - docker run -e CI=true shayankureshi/react-test npm test
after_success:
 - docker build -t shayankureshi/multi-client ./client
 - docker build -t shayankureshi/multi-nginx ./nginx
 - docker build -t shayankureshi/multi-server ./server
 - docker build -t shayankureshi/multi-worker ./worker
 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push it to docker hub
 - docker push shayankureshi/multi-client
 - docker push shayankureshi/multi-nginx
 - docker push shayankureshi/multi-server
 - docker push shayankureshi/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-491521737088"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"